# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='person.proto',
  package='Person',
  syntax='proto3',
  serialized_options=_b('\252\002\017TestGrpcService'),
  serialized_pb=_b('\n\x0cperson.proto\x12\x06Person\"1\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1e\n\x10GetPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x43\n\nPersonServ\x12\x35\n\tGetPerson\x12\x18.Person.GetPersonRequest\x1a\x0e.Person.PersonB\x12\xaa\x02\x0fTestGrpcServiceb\x06proto3')
)




_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='Person.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Person.Person.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Person.Person.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='Person.Person.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=73,
)


_GETPERSONREQUEST = _descriptor.Descriptor(
  name='GetPersonRequest',
  full_name='Person.GetPersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Person.GetPersonRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['GetPersonRequest'] = _GETPERSONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:Person.Person)
  })
_sym_db.RegisterMessage(Person)

GetPersonRequest = _reflection.GeneratedProtocolMessageType('GetPersonRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPERSONREQUEST,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:Person.GetPersonRequest)
  })
_sym_db.RegisterMessage(GetPersonRequest)


DESCRIPTOR._options = None

_PERSONSERV = _descriptor.ServiceDescriptor(
  name='PersonServ',
  full_name='Person.PersonServ',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=174,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPerson',
    full_name='Person.PersonServ.GetPerson',
    index=0,
    containing_service=None,
    input_type=_GETPERSONREQUEST,
    output_type=_PERSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSONSERV)

DESCRIPTOR.services_by_name['PersonServ'] = _PERSONSERV

# @@protoc_insertion_point(module_scope)
