# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import person_pb2 as person__pb2


class PersonServStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPerson = channel.unary_unary(
        '/Person.PersonServ/GetPerson',
        request_serializer=person__pb2.GetPersonRequest.SerializeToString,
        response_deserializer=person__pb2.Person.FromString,
        )


class PersonServServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PersonServServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPerson': grpc.unary_unary_rpc_method_handler(
          servicer.GetPerson,
          request_deserializer=person__pb2.GetPersonRequest.FromString,
          response_serializer=person__pb2.Person.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Person.PersonServ', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
